# Generated by Django 5.2.4 on 2025-07-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_salesorder_salesorderitem_salesorder_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField()),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('delivered', models.BooleanField(default=False)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.salesorder')),
            ],
        ),
    ]
