# Generated by Django 5.2.4 on 2025-07-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_salesorderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
